version: "3.9"

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: odoo
      POSTGRES_USER: odoo
      POSTGRES_PASSWORD: odoo
    ports:
      - "5455:5432"
    volumes:
      - odoo-db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U odoo -d odoo"]
      interval: 5s
      timeout: 5s
      retries: 5

  odoo:
    image: odoo:16
    depends_on:
      db:
        condition: service_healthy
    environment:
      - HOST=db
      - USER=odoo
      - PASSWORD=odoo
    command: >
      odoo --db_host=db --db_user=odoo --db_password=odoo
      --database=odoo --init=base --update=all --without-demo=all
      --dev=reload
    volumes:
      - ./extra-addons:/mnt/extra-addons
    ports:
      - "8015:8069"

volumes:
  odoo-db-data: